/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Buscador extends javax.swing.JFrame {

    /**
     * Creates new form Buscador
     */
    public Buscador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etPath = new javax.swing.JTextField();
        bEscogerArchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etExtension = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        bLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Explorador básico");

        etPath.setEditable(false);
        etPath.setFocusable(false);
        etPath.setName("tfPath"); // NOI18N

        bEscogerArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carpeta.png"))); // NOI18N
        bEscogerArchivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bEscogerArchivo.setName("bFileChoser"); // NOI18N
        bEscogerArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEscogerArchivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Ruta del Fichero");

        jLabel2.setText("Extensión");

        etExtension.setEditable(false);
        etExtension.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                etExtensionInputMethodTextChanged(evt);
            }
        });
        etExtension.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                etExtensionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etExtensionKeyTyped(evt);
            }
        });

        Tabla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Extensión", "Tamaño", "F/D"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.getTableHeader().setResizingAllowed(false);
        Tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setResizable(false);
            Tabla.getColumnModel().getColumn(1).setResizable(false);
            Tabla.getColumnModel().getColumn(2).setResizable(false);
            Tabla.getColumnModel().getColumn(3).setResizable(false);
        }

        bLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/limpiar.png"))); // NOI18N
        bLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bLimpiar.setEnabled(false);
        bLimpiar.setName("bFileChoser"); // NOI18N
        bLimpiar.setRolloverEnabled(false);
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(etExtension, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                                    .addComponent(etPath))
                                .addGap(75, 75, 75)
                                .addComponent(bEscogerArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(etPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(bEscogerArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEscogerArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEscogerArchivoActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int seleccion = fc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            etPath.setText(f.getAbsolutePath());
            rellenarTabla(f);
        }
        etExtension.setEditable(true);
        bLimpiar.setEnabled(true);
    }//GEN-LAST:event_bEscogerArchivoActionPerformed

    private void etExtensionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etExtensionKeyPressed
        Character letra = evt.getKeyChar();
        if (Character.isLetter(letra) || Character.isDigit(letra) || (evt.getKeyChar() == KeyEvent.VK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_SHIFT)) {
            File[] listaFiles;
            if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
                if (etExtension.getText().length() == 1) {
                    File f = new File(etPath.getText());
                    rellenarTabla(f);
                } else {
                    if (etExtension.getText().length() != 0) {
                        String texto = etExtension.getText().substring(0, etExtension.getText().length() - 1);
                        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
                        int filas = Tabla.getRowCount();
                        for (int i = 0; i < filas; i++) {
                            model.removeRow(0);
                        }
                        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
                        File f = new File(etPath.getText());
                        if (f.isDirectory()) {
                            listaFiles = f.listFiles();
                            for (File f1 : listaFiles) {
                                String extension = "";
                                int i = f1.getName().lastIndexOf('.');
                                if (i > 0) {
                                    extension = f1.getName().substring(i + 1);
                                }
                                if (extension.startsWith(texto)) {
                                    anadirFila(f1);
                                }
                            }
                        }
                    }
                }
            } else {
                if (evt.getKeyCode() == KeyEvent.VK_SPACE && etExtension.getText().length() == 0) {
                    String texto = etExtension.getText() + evt.getKeyChar();
                    DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
                    int filas = Tabla.getRowCount();
                    for (int i = 0; i < filas; i++) {
                        model.removeRow(0);
                    }
                    if (!texto.equals(" ")) {
                        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
                        File f = new File(etPath.getText());
                        if (f.isDirectory()) {
                            listaFiles = f.listFiles();
                            for (File f1 : listaFiles) {
                                String extension = "";
                                int i = f1.getName().lastIndexOf('.');
                                if (i > 0) {
                                    extension = f1.getName().substring(i + 1);
                                }
                                if (extension.startsWith(texto)) {
                                    anadirFila(f1);
                                }
                            }
                        }
                    } else {
                        DefaultTableModel modelo1 = (DefaultTableModel) Tabla.getModel();
                        int filass = Tabla.getRowCount();
                        for (int i = 0; i < filas; i++) {
                            modelo1.removeRow(0);
                        }
                    }
                } else {
                    String texto = etExtension.getText() + evt.getKeyChar();

                    DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
                    int filas = Tabla.getRowCount();
                    for (int i = 0; i < filas; i++) {
                        model.removeRow(0);
                    }
                    if (!texto.equals("")) {
                        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
                        File f = new File(etPath.getText());
                        if (f.isDirectory()) {
                            listaFiles = f.listFiles();
                            for (File f1 : listaFiles) {
                                String extension = "";
                                int i = f1.getName().lastIndexOf('.');
                                if (i > 0) {
                                    extension = f1.getName().substring(i + 1);
                                }
                                if (extension.startsWith(texto)) {
                                    anadirFila(f1);
                                }
                            }
                        }
                    } else {
                        File f = new File(etPath.getText());
                        rellenarTabla(f);
                    }
                }
            }
        } else {
            getToolkit().beep();
        }
    }//GEN-LAST:event_etExtensionKeyPressed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        modelo.setRowCount(0);
        bLimpiar.setEnabled(false);
        etExtension.setEditable(false);
        etPath.setText("");
        etExtension.setText("");
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void etExtensionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etExtensionKeyTyped
    }//GEN-LAST:event_etExtensionKeyTyped

    private void etExtensionInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_etExtensionInputMethodTextChanged
    }//GEN-LAST:event_etExtensionInputMethodTextChanged

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscador().setVisible(true);
            }
        });

    }

    public void rellenarTabla(File f) {
        File[] listaFiles;
        try {
            DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
            int filas = Tabla.getRowCount();
            for (int i = 0; i < filas; i++) {
                modelo.removeRow(0);
            }
            if (f.exists()) {
                if (f.isDirectory()) {
                    listaFiles = f.listFiles();
                    for (File auxFile : listaFiles) {
                        anadirFila(auxFile);
                    }
                } else {
                    anadirFila(f);
                }
            }
        } catch (NullPointerException e) {
            System.out.println("Ha ocurrido un error: " + e.getMessage());
        } catch (SecurityException e) {
            System.out.println("Ha ocurrido un error: " + e.getMessage());
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Ha ocurrido un error: " + e.getMessage());
        }
    }

    public void anadirFila(File f) {
        try {
            DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
            String fe = "";
            int i = f.getName().lastIndexOf('.');
            if (i > 0) {
                fe = f.getName().substring(i + 1);
            }
            String fod = "";
            if (f.isDirectory()) {
                fod = "D";
            } else {
                fod = "F";
            }
            modelo.addRow(new Object[]{f.getName(), fe, "" + f.length(), fod});
        } catch (NullPointerException e) {
            System.out.println("Ha ocurrido un error: " + e.getMessage());
        } catch (SecurityException e) {
            System.out.println("Ha ocurrido un error: " + e.getMessage());
        }
    }

    public void filtroExtension(java.awt.event.KeyEvent evt) {
        File[] listaFiles;
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            if (etExtension.getText().length() == 1) {
                File f = new File(etPath.getText());
                rellenarTabla(f);
            } else {
                if (etExtension.getText().trim().length() != 0) {
                    String texto = etExtension.getText().trim().substring(0, etExtension.getText().trim().length() - 1);
                    DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
                    int filas = Tabla.getRowCount();
                    for (int i = 0; i < filas; i++) {
                        model.removeRow(0);
                    }
                    DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
                    File f = new File(etPath.getText());
                    if (f.isDirectory()) {
                        listaFiles = f.listFiles();
                        for (File f1 : listaFiles) {
                            String extension = "";
                            int i = f1.getName().lastIndexOf('.');
                            if (i > 0) {
                                extension = f1.getName().substring(i + 1);
                            }
                            if (extension.startsWith(texto)) {
                                anadirFila(f1);
                            }
                        }
                    }
                }
            }
        } else {
            String texto = etExtension.getText().trim() + evt.getKeyChar();
            DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
            int filas = Tabla.getRowCount();
            for (int i = 0; i < filas; i++) {
                model.removeRow(0);
            }
            if (!texto.trim().equals("")) {
                DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
                File f = new File(etPath.getText());
                if (f.isDirectory()) {
                    listaFiles = f.listFiles();
                    for (File f1 : listaFiles) {
                        String extension = "";
                        int i = f1.getName().lastIndexOf('.');
                        if (i > 0) {
                            extension = f1.getName().substring(i + 1);
                        }
                        if (extension.startsWith(texto)) {
                            anadirFila(f1);
                        }
                    }
                }
            } else {
                File f = new File(etPath.getText());
                rellenarTabla(f);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton bEscogerArchivo;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JFormattedTextField etExtension;
    private javax.swing.JTextField etPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
